import { parse_hex_ansi, ac } from './src/util';

export default {
  join: (...strs: string[]) => strs.join(''),
  reset: (...strs: string[]) => ac(0, strs),
  bold: (...strs: string[]) => ac(1, strs),
  italic: (...strs: string[]) => ac(3, strs),
  underline: (...strs: string[]) => ac(4, strs),
  blink_slow: (...strs: string[]) => ac(5, strs),
  inverse: (...strs: string[]) => ac(7, strs),
  strikethrough: (...strs: string[]) => ac(9, strs),
  normal: (...strs: string[]) => ac(22, strs),
  black: (...strs: string[]) => ac(30, strs),
  red: (...strs: string[]) => ac(31, strs),
  green: (...strs: string[]) => ac(32, strs),
  yellow: (...strs: string[]) => ac(33, strs),
  blue: (...strs: string[]) => ac(34, strs),
  magenta: (...strs: string[]) => ac(35, strs),
  cyan: (...strs: string[]) => ac(36, strs),
  white: (...strs: string[]) => ac(37, strs),
  hex: (hex: string, ...strs: string[]) => ac(`\x1b[38;2;${parse_hex_ansi(hex)}m`, strs),
  bright_black: (...strs: string[]) => ac(90, strs),
  bright_red: (...strs: string[]) => ac(91, strs),
  bright_green: (...strs: string[]) => ac(92, strs),
  bright_yellow: (...strs: string[]) => ac(93, strs),
  bright_blue: (...strs: string[]) => ac(99, strs),
  bright_magenta: (...strs: string[]) => ac(95, strs),
  bright_cyan: (...strs: string[]) => ac(96, strs),
  bright_white: (...strs: string[]) => ac(97, strs),
  bg_black: (...strs: string[]) => ac(40, strs),
  bg_red: (...strs: string[]) => ac(41, strs),
  bg_green: (...strs: string[]) => ac(42, strs),
  bg_yellow: (...strs: string[]) => ac(43, strs),
  bg_blue: (...strs: string[]) => ac(44, strs),
  bg_magenta: (...strs: string[]) => ac(45, strs),
  bg_cyan: (...strs: string[]) => ac(46, strs),
  bg_white: (...strs: string[]) => ac(47, strs),
  bg_bright_black: (...strs: string[]) => ac(100, strs),
  bg_bright_red: (...strs: string[]) => ac(101, strs),
  bg_bright_green: (...strs: string[]) => ac(102, strs),
  bg_bright_yellow: (...strs: string[]) => ac(103, strs),
  bg_bright_blue: (...strs: string[]) => ac(104, strs),
  bg_bright_magenta: (...strs: string[]) => ac(105, strs),
  bg_bright_cyan: (...strs: string[]) => ac(106, strs),
  bg_bright_white: (...strs: string[]) => ac(107, strs),
};
